import type {
  Customer,
  Engineer,
  Invoice,
  Job,
  ServiceCategory,
  UKPart,
} from "@/types/domain";

export const SERVICES: { id: ServiceCategory; name: string; icon: string; blurb: string; from: number }[] = [
  { id: "plumbing", name: "Plumbing", icon: "Wrench", blurb: "Leaks, burst pipes, blockages and bathroom fittings.", from: 85 },
  { id: "electrical", name: "Electrical", icon: "Zap", blurb: "Fault finding, rewiring, consumer units and sockets.", from: 95 },
  { id: "heating", name: "Heating & Gas", icon: "Flame", blurb: "Boiler repair, central heating and Gas Safe servicing.", from: 110 },
  { id: "cleaning", name: "Cleaning", icon: "Sparkles", blurb: "Deep cleaning, end-of-tenancy cleaning and regular visits.", from: 55 },
  { id: "locksmith", name: "Locksmith", icon: "KeyRound", blurb: "Lockouts, lock changes and door-lock repair.", from: 90 },
];

export const ENGINEERS: Engineer[] = [
  {
    id: "eng-1",
    name: "James Walker",
    avatar: "JW",
    rating: 4.9,
    jobsCompleted: 812,
    skills: ["plumbing", "heating"],
    certifications: [{ name: "Gas Safe Registered Engineer", expiresAt: "2027-03-01" }],
    status: "available",
    position: { lat: 51.5231, lng: -0.1439 },
    vanReg: "PL21 KLM",
    phone: "+44 7700 900101",
    workloadToday: 3,
    maxWorkload: 6,
    homeBase: "Camden, London",
    employedSince: "2019-04-01",
  },
  {
    id: "eng-2",
    name: "Sophie Bennett",
    avatar: "SB",
    rating: 4.8,
    jobsCompleted: 654,
    skills: ["electrical"],
    certifications: [{ name: "NICEIC Approved Contractor", expiresAt: "2026-11-15" }],
    status: "en_route",
    position: { lat: 51.4975, lng: -0.1357 },
    vanReg: "EL09 PNR",
    phone: "+44 7700 900102",
    workloadToday: 4,
    maxWorkload: 6,
    homeBase: "Westminster, London",
    employedSince: "2020-09-12",
  },
  {
    id: "eng-3",
    name: "Oliver Hughes",
    avatar: "OH",
    rating: 4.7,
    jobsCompleted: 431,
    skills: ["plumbing", "locksmith"],
    certifications: [{ name: "City & Guilds Level 3 Plumbing", expiresAt: "2028-01-01" }],
    status: "busy",
    position: { lat: 51.5416, lng: -0.1022 },
    vanReg: "PL55 JFD",
    phone: "+44 7700 900103",
    workloadToday: 5,
    maxWorkload: 6,
    homeBase: "Islington, London",
    employedSince: "2021-02-20",
  },
  {
    id: "eng-4",
    name: "Emily Carter",
    avatar: "EC",
    rating: 5.0,
    jobsCompleted: 298,
    skills: ["cleaning"],
    certifications: [{ name: "BICSc Cleaning Professional", expiresAt: "2027-06-01" }],
    status: "available",
    position: { lat: 51.5035, lng: -0.0804 },
    vanReg: "CL02 ABL",
    phone: "+44 7700 900104",
    workloadToday: 2,
    maxWorkload: 8,
    homeBase: "Southwark, London",
    employedSince: "2022-05-03",
  },
  {
    id: "eng-5",
    name: "Daniel Wilson",
    avatar: "DW",
    rating: 4.6,
    jobsCompleted: 520,
    skills: ["electrical", "heating"],
    certifications: [{ name: "Gas Safe Heating Engineer", expiresAt: "2026-09-20" }],
    status: "offline",
    position: { lat: 51.4613, lng: -0.1156 },
    vanReg: "EL41 TWF",
    phone: "+44 7700 900105",
    workloadToday: 0,
    maxWorkload: 6,
    homeBase: "Brixton, London",
    employedSince: "2018-11-11",
  },
  {
    id: "eng-6",
    name: "Grace Taylor",
    avatar: "GT",
    rating: 4.9,
    jobsCompleted: 377,
    skills: ["locksmith", "plumbing"],
    certifications: [{ name: "Master Locksmiths Association Member", expiresAt: "2027-08-01" }],
    status: "available",
    position: { lat: 51.5136, lng: -0.0984 },
    vanReg: "LK18 NKW",
    phone: "+44 7700 900106",
    workloadToday: 1,
    maxWorkload: 7,
    homeBase: "City of London",
    employedSince: "2023-01-09",
  },
];

export const CUSTOMERS: Customer[] = [
  {
    id: "cus-1",
    name: "Amelia Brown",
    email: "amelia.brown@example.co.uk",
    phone: "+44 7700 900201",
    address: { line1: "14 Maple Street", city: "London", postcode: "NW1 6XE", lat: 51.5237, lng: -0.1585 },
    properties: 1,
    lifetimeValue: 1240,
    jobsCount: 4,
    tags: ["repeat", "landlord"],
    memberSince: "2023-02-14",
  },
  {
    id: "cus-2",
    name: "George Evans",
    email: "george.evans@example.co.uk",
    phone: "+44 7700 900202",
    address: { line1: "88 Eaton Square", city: "London", postcode: "SW1W 9AN", lat: 51.4985, lng: -0.1484 },
    properties: 2,
    lifetimeValue: 2875,
    jobsCount: 7,
    tags: ["landlord", "priority"],
    memberSince: "2021-06-30",
  },
  {
    id: "cus-3",
    name: "Charlotte King",
    email: "charlotte.king@example.co.uk",
    phone: "+44 7700 900203",
    address: { line1: "Flat 22, Borough High Street", city: "London", postcode: "SE1 1XN", lat: 51.5043, lng: -0.0916 },
    properties: 1,
    lifetimeValue: 485,
    jobsCount: 2,
    tags: ["new"],
    memberSince: "2025-11-02",
  },
  {
    id: "cus-4",
    name: "Harry Clarke",
    email: "harry.clarke@example.co.uk",
    phone: "+44 7700 900204",
    address: { line1: "5 Fleet Street", city: "London", postcode: "EC4Y 1AA", lat: 51.5141, lng: -0.107 },
    properties: 1,
    lifetimeValue: 210,
    jobsCount: 1,
    tags: ["new"],
    memberSince: "2026-01-18",
  },
];

export const UK_PARTS: UKPart[] = [
  { id: "p1", name: "Combination boiler control board", category: "heating", supplier: "London Heating Supplies", price: 185, unit: "unit", lastUpdated: "2026-07-28" },
  { id: "p2", name: "22mm compression fitting", category: "plumbing", supplier: "City Plumbing", price: 4.5, unit: "each", lastUpdated: "2026-07-30" },
  { id: "p3", name: "10-way consumer unit with RCD", category: "electrical", supplier: "CEF", price: 145, unit: "unit", lastUpdated: "2026-07-29" },
  { id: "p4", name: "Anti-snap euro cylinder lock", category: "locksmith", supplier: "London Lock Centre", price: 42, unit: "each", lastUpdated: "2026-07-25" },
  { id: "p5", name: "15mm isolation valve", category: "plumbing", supplier: "City Plumbing", price: 8.5, unit: "each", lastUpdated: "2026-07-27" },
  { id: "p6", name: "32A single-pole circuit breaker", category: "electrical", supplier: "CEF", price: 14, unit: "each", lastUpdated: "2026-07-30" },
  { id: "p7", name: "Boiler pressure relief valve", category: "heating", supplier: "London Heating Supplies", price: 28, unit: "each", lastUpdated: "2026-07-26" },
  { id: "p8", name: "Professional eco cleaning kit", category: "cleaning", supplier: "UK Hygiene Supplies", price: 18, unit: "kit", lastUpdated: "2026-07-24" },
];

function iso(daysFromNow: number, hour = 9): string {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const JOBS: Job[] = [
  {
    id: "job-1",
    reference: "TW-48213",
    customerId: "cus-1",
    customerName: "Amelia Brown",
    customerEmail: "amelia.brown@example.co.uk",
    customerPhone: "+44 7700 900201",
    address: { line1: "14 Maple Street", city: "London", postcode: "NW1 6XE", lat: 51.5237, lng: -0.1585 },
    service: "plumbing",
    issue: "Kitchen tap leaking under the sink, water pooling in the cupboard.",
    urgency: "today",
    status: "en_route",
    createdAt: iso(0, 8),
    scheduledWindow: { start: iso(0, 11), end: iso(0, 13) },
    engineerId: "eng-1",
    etaMinutes: 18,
    priceEstimate: { low: 110, high: 220 },
    photos: [],
    notes: "Access via front door, key safe code given.",
    timeline: [
      { status: "lead", at: iso(0, 8) },
      { status: "quoted", at: iso(0, 8) },
      { status: "approved", at: iso(0, 8) },
      { status: "assigned", at: iso(0, 9) },
      { status: "en_route", at: iso(0, 10) },
    ],
    accessNotes: "Key safe, code sent via SMS.",
  },
  {
    id: "job-2",
    reference: "TW-48214",
    customerId: "cus-2",
    customerName: "George Evans",
    customerEmail: "george.evans@example.co.uk",
    customerPhone: "+44 7700 900202",
    address: { line1: "88 Eaton Square", city: "London", postcode: "SW1W 9AN", lat: 51.4985, lng: -0.1484 },
    service: "electrical",
    issue: "Full power loss to upstairs sockets, tripping consumer unit.",
    urgency: "emergency",
    status: "unassigned",
    createdAt: iso(0, 9),
    scheduledWindow: null,
    engineerId: null,
    etaMinutes: null,
    priceEstimate: { low: 145, high: 380 },
    photos: [],
    notes: "Tenant reports burning smell near the unit - treat as priority.",
    timeline: [{ status: "lead", at: iso(0, 9) }],
  },
  {
    id: "job-3",
    reference: "TW-48197",
    customerId: "cus-3",
    customerName: "Charlotte King",
    customerEmail: "charlotte.king@example.co.uk",
    customerPhone: "+44 7700 900203",
    address: { line1: "Flat 22, Borough High Street", city: "London", postcode: "SE1 1XN", lat: 51.5043, lng: -0.0916 },
    service: "cleaning",
    issue: "Move-out deep clean for a two-bedroom apartment.",
    urgency: "scheduled",
    status: "completed",
    createdAt: iso(-3, 9),
    scheduledWindow: { start: iso(-1, 9), end: iso(-1, 12) },
    engineerId: "eng-4",
    etaMinutes: null,
    priceEstimate: { low: 180, high: 280 },
    photos: [],
    notes: "Keys with letting agent.",
    timeline: [
      { status: "lead", at: iso(-3, 9) },
      { status: "quoted", at: iso(-3, 10) },
      { status: "approved", at: iso(-3, 12) },
      { status: "assigned", at: iso(-2, 9) },
      { status: "en_route", at: iso(-1, 8) },
      { status: "arrived", at: iso(-1, 9) },
      { status: "in_progress", at: iso(-1, 9) },
      { status: "completed", at: iso(-1, 12) },
      { status: "invoiced", at: iso(-1, 13) },
    ],
    rating: { stars: 5, comment: "Spotless, on time, very friendly." },
  },
  {
    id: "job-4",
    reference: "TW-48180",
    customerId: "cus-4",
    customerName: "Harry Clarke",
    customerEmail: "harry.clarke@example.co.uk",
    customerPhone: "+44 7700 900204",
    address: { line1: "5 Fleet Street", city: "London", postcode: "EC4Y 1AA", lat: 51.5141, lng: -0.107 },
    service: "locksmith",
    issue: "Locked out; the front-door cylinder lock is jammed.",
    urgency: "emergency",
    status: "paid",
    createdAt: iso(-6, 18),
    scheduledWindow: null,
    engineerId: "eng-6",
    etaMinutes: null,
    priceEstimate: { low: 120, high: 245 },
    photos: [],
    notes: "",
    timeline: [
      { status: "lead", at: iso(-6, 18) },
      { status: "assigned", at: iso(-6, 18) },
      { status: "en_route", at: iso(-6, 18) },
      { status: "arrived", at: iso(-6, 19) },
      { status: "completed", at: iso(-6, 19) },
      { status: "invoiced", at: iso(-6, 20) },
      { status: "paid", at: iso(-6, 20) },
    ],
    rating: { stars: 4, comment: "Quick response, a bit pricey but fair for a late call-out." },
  },
  {
    id: "job-5",
    reference: "TW-48221",
    customerId: "cus-1",
    customerName: "Amelia Brown",
    customerEmail: "amelia.brown@example.co.uk",
    customerPhone: "+44 7700 900201",
    address: { line1: "14 Maple Street", city: "London", postcode: "NW1 6XE", lat: 51.5237, lng: -0.1585 },
    service: "heating",
    issue: "Annual gas boiler service is due.",
    urgency: "scheduled",
    status: "assigned",
    createdAt: iso(0, 9),
    scheduledWindow: { start: iso(2, 10), end: iso(2, 12) },
    engineerId: "eng-1",
    etaMinutes: null,
    priceEstimate: { low: 110, high: 195 },
    photos: [],
    notes: "",
    timeline: [
      { status: "lead", at: iso(0, 9) },
      { status: "approved", at: iso(0, 9) },
      { status: "assigned", at: iso(0, 9) },
    ],
  },
  {
    id: "job-6",
    reference: "TW-48205",
    customerId: "cus-2",
    customerName: "George Evans",
    customerEmail: "george.evans@example.co.uk",
    customerPhone: "+44 7700 900202",
    address: { line1: "12 Clapham Park Road", city: "London", postcode: "SW4 7BB", lat: 51.4622, lng: -0.1387 },
    service: "plumbing",
    issue: "Low water pressure in the upstairs bathroom; pipes need checking.",
    urgency: "today",
    status: "quote_requested",
    createdAt: iso(0, 7),
    scheduledWindow: null,
    engineerId: null,
    etaMinutes: null,
    priceEstimate: { low: 85, high: 190 },
    photos: [],
    notes: "",
    timeline: [{ status: "lead", at: iso(0, 7) }, { status: "quote_requested", at: iso(0, 7) }],
  },
];

export const INVOICES: Invoice[] = [
  {
    id: "inv-1",
    number: "TW-INV-1042",
    jobId: "job-3",
    issuedAt: iso(-1, 13),
    dueAt: iso(13, 13),
    lines: [
      { id: "l1", description: "End-of-tenancy clean - two-bedroom flat", qty: 1, unitPrice: 220, type: "labour" },
      { id: "l2", description: "Cleaning consumables kit", qty: 1, unitPrice: 18, type: "part" },
    ],
    vatRate: 0.2,
    status: "sent",
  },
  {
    id: "inv-2",
    number: "TW-INV-1039",
    jobId: "job-4",
    issuedAt: iso(-6, 20),
    dueAt: iso(-6, 20),
    lines: [
      { id: "l1", description: "Emergency locksmith visit (evening)", qty: 1, unitPrice: 145, type: "callout" },
      { id: "l2", description: "Anti-snap euro cylinder lock", qty: 1, unitPrice: 42, type: "part" },
    ],
    vatRate: 0.2,
    status: "paid",
    paidAt: iso(-6, 20),
    paymentMethod: "card",
  },
];

export const TESTIMONIALS = [
  { name: "Lucy Morgan", area: "Camden", quote: "Booked online in two minutes and the engineer arrived within the hour. Genuinely impressed.", rating: 5, service: "Plumbing" },
  { name: "Thomas Reed", area: "Westminster", quote: "The live tracking meant I did not have to wait all day wondering when they would arrive.", rating: 5, service: "Electrical" },
  { name: "Olivia Harris", area: "Southwark", quote: "Transparent pricing before anyone left the depot. No surprises on the invoice.", rating: 4, service: "Heating" },
];
